version: '3.8'

services:
  backend:
    build:
      context: ./backend
      target: dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && rails s -b 0.0.0.0"
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./backend:/usr/src/app
    environment:
      RAILS_ENV: ${RAILS_ENV}
      DB_NAME: ${DB_NAME}
      DB_TEST_NAME: ${DB_TEST_NAME}
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 3306

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
